{% set version = "0.12.0" %}

package:
  name: meson-python
  version: {{ version }}

source:
  url: https://github.com/mesonbuild/meson-python/archive/refs/tags/{{ version }}.tar.gz
  sha256: 7fed5b541507b28363e38e9389f939840ea4dec8dcb72143006ded7b90a052e1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - colorama
    - meson >=0.63.3
    - ninja
    - pyproject-metadata >=0.6.1
    - pip
    - python >=3.7
    - tomli >=1.0.0
    - typing-extensions >=3.7.4
  run:
    - colorama
    - meson >=0.63.3
    - ninja
    - pyproject-metadata >=0.6.1
    - python >=3.7
    - tomli >=1.0.0
    - typing-extensions >=3.7.4
    - wheel >=0.36.0

test:
  imports:
    - mesonpy
  commands:
    - pip check
    # PEP518 tests will always fail with conda setup
    - rm tests/test_pep518.py
    - pytest tests -vv
  source_files:
    - tests/
    - docs/
  requires:
    - {{ compiler('c') }}
    - cython
    - git
    - gitpython
    - patchelf  # [linux]
    - pip
    - pytest
    - pytest-mock

about:
  home: https://github.com/mesonbuild/meson-python
  doc_url: https://meson-python.readthedocs.io/en/latest/
  summary: Meson Python build backend (PEP 517)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
    - rgommers
