{% set version = "0.12.1" %}

package:
  name: meson-python
  version: {{ version }}

source:
  url: https://github.com/mesonbuild/meson-python/archive/refs/tags/{{ version }}.tar.gz
  sha256: 8e9c726aeba817c21209fc89eac38ca069e79b5238ac023f83a0be507a160804
  patches:
    # backport https://github.com/mesonbuild/meson-python/pull/322 for cross-compilation support
    - patches/0001-ENH-do-not-check-extension-module-file-name-against-.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - colorama
    - meson >=0.63.3
    - ninja
    - pyproject-metadata >=0.6.1
    - pip
    - python >=3.7
    - tomli >=1.0.0
    - typing-extensions >=3.7.4
  run:
    - colorama
    - meson >=0.63.3
    - ninja
    - pyproject-metadata >=0.6.1
    - python >=3.7
    - tomli >=1.0.0
    - typing-extensions >=3.7.4
    - wheel >=0.36.0

test:
  imports:
    - mesonpy
  commands:
    - pip check
    # PEP518 tests will always fail with conda setup
    - rm tests/test_pep518.py
    - pytest tests -vv
  source_files:
    - tests/
    - docs/
  requires:
    - {{ compiler('c') }}
    - cython
    - git
    - gitpython
    - patchelf  # [linux]
    - pip
    - pytest
    - pytest-mock

about:
  home: https://github.com/mesonbuild/meson-python
  doc_url: https://meson-python.readthedocs.io/en/latest/
  summary: Meson Python build backend (PEP 517)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
    - rgommers
