{% set version = "0.10.0" %}

package:
  name: meson-python
  version: {{ version }}

source:
  url: https://github.com/FFY00/meson-python/archive/refs/tags/{{ version }}.tar.gz
  sha256: e3e79e592b8ad79e22292ab76b7fcde2af3aeebc4bd76f687fb19e5672908a40
  patches:
    - patches/0001-fix-overdependency-on-ninja.patch
    - patches/0002-fix-for-executable-bit-test.patch
    - patches/0003-meson_backport.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - colorama
    - meson >=0.63.0
    - ninja
    - pyproject-metadata >=0.6.0
    - pip
    - python >=3.7
    - tomli >=1.0.0
    - typing-extensions >=3.7.4
  run:
    - colorama
    - meson >=0.62.0
    - ninja
    - pyproject-metadata >=0.6.0
    - python >=3.7
    - tomli >=1.0.0
    - typing-extensions >=3.7.4
    - wheel >=0.36.0

test:
  imports:
    - mesonpy
  commands:
    - pip check
    - pytest tests -vv
  source_files:
    - tests/
    - docs/
  requires:
    - {{ compiler('c') }}
    - cython
    - git
    - gitpython
    - patchelf  # [linux]
    - pip
    - pytest
    - pytest-mock

about:
  home: https://github.com/FFY00/meson-python
  doc_url: https://meson-python.readthedocs.io/en/latest/
  summary: Meson Python build backend (PEP 517)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
    - rgommers
