{% set name = "meson-python" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/meson_python-{{ version }}.tar.gz
  sha256: fdb5fbb3ab6d7536afffea8fb7d0984446f8b79bc70b3fbc980e43bd5f356df3
  patches:
    - ninja-overdep.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - colorama
    - meson >=0.60.0
    - ninja
    - pep621 >=0.3.0
    - pip
    - python >=3.7
    - tomli >=1.0.0
    - typing-extensions >=3.7.4
  run:
    - colorama
    - meson >=0.60.0
    - ninja
    - pep621 >=0.3.0
    - python >=3.7
    - tomli >=1.0.0
    - typing-extensions >=3.7.4
    - wheel >=0.36.0

test:
  imports:
    - mesonpy
  commands:
    - pip check
    - pytest tests -vv -k "not test_contents_unstaged"
  source_files:
    - tests/
  requires:
    - {{ compiler('c') }}
    - git
    - gitpython
    - patchelf  # [linux]
    - pip
    - pytest
    - pytest-mock

about:
  home: https://github.com/FFY00/meson-python
  doc_url: https://meson-python.readthedocs.io/en/latest/
  summary: Meson Python build backend (PEP 517)
  license: EUPL-1.2
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
    - rgommers
