context:
  version: "0.20.0"

package:
  name: meson-python
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/8b/f0/d794d7ed8a843a8a8947768f3b329d1e8601222dc95d930f4a5f9706cd6c/meson_python-${{ version }}.tar.gz
  sha256: 6d9726ae6cd37e22f210c74b364b30180a68c20442e97ff09f3c566a414af738

build:
  number: 0
  noarch: python
  # Avoid packaging a test package with a non-ascii filename, since that
  # might not install depending on the target machine (see gh-29)
  script: rm -rf tests/packages/encoding && ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - meson >=0.64.0
    - ninja
    - packaging >=23.2
    - pyproject-metadata >=0.9.0
    - pip
    - python ${{ python_min }}.*
    - tomli >=1.0.0
  run:
    - meson >=0.64.0
    - ninja
    - packaging >=23.2
    - pyproject-metadata >=0.9.0
    - python >=${{ python_min }}
    - tomli >=1.0.0

tests:
  - python:
      imports:
        - mesonpy
  - files:
      source:
        - tests/
        - docs/
        - pyproject.toml
    requirements:
      run:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - cython
        - git
        - gitpython
        - if: linux
          then: patchelf
        - pip
        - python ${{ python_min }}.*
        - pytest
        - pytest-mock
        - wheel
    script:
      - pip check
      - export CPPFLAGS=${CPPFLAGS//-DNDEBUG/}
      - pytest tests -vv -k "not test_encoding"

about:
  summary: Meson Python build backend (PEP 517)
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/mesonbuild/meson-python
  documentation: https://meson-python.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - awvwgk
    - rgommers
