context:
  version: 0.19.0

package:
  name: meson-python
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/meson-python/meson_python-${{ version }}.tar.gz
  sha256: 9959d198aa69b57fcfd354a34518c6f795b781a73ed0656f4d01660160cc2553

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - meson >=0.64.0
    - ninja
    - packaging >=23.2
    - pyproject-metadata >=0.9.0
    - pip
    - python ${{ python_min }}.*
    - tomli >=1.0.0
  run:
    - meson >=0.64.0
    - ninja
    - packaging >=23.2
    - pyproject-metadata >=0.9.0
    - python >=${{ python_min }}
    - tomli >=1.0.0

tests:
  - python:
      imports:
        - mesonpy
  - files:
      source:
        - tests/
        - docs/
        - pyproject.toml
    requirements:
      run:
        - ${{ compiler('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - cython
        - git
        - gitpython
        - if: linux
          then: patchelf
        - pip
        - python ${{ python_min }}.*
        - pytest
        - pytest-mock
        - wheel
    script:
      - pip check
      - export CPPFLAGS=${CPPFLAGS//-DNDEBUG/}
      - pytest tests -vv

about:
  summary: Meson Python build backend (PEP 517)
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/mesonbuild/meson-python
  documentation: https://meson-python.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - awvwgk
    - rgommers
