schema_version: 1

context:
  version: 0.17.1

package:
  name: meson-python
  version: ${{ version }}

source:
  url: https://github.com/mesonbuild/meson-python/archive/refs/tags/${{ version }}.tar.gz
  sha256: d533356468000e6f126215dded75dd9b07c7cbe14ca9f78c51791d4172b6e4a5

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - meson >=0.63.3
    - ninja
    - packaging >=19.0
    - pyproject-metadata >=0.7.1
    - pip
    - python >=3.7
    - tomli >=1.0.0
  run:
    - meson >=0.63.3
    - ninja
    - packaging >=19.0
    - pyproject-metadata >=0.7.1
    - python >=3.7
    - tomli >=1.0.0

tests:
  - python:
      imports:
        - mesonpy
  - files:
      source:
        - tests/
        - docs/
        - pyproject.toml
    requirements:
      run:
        - ${{ compiler('c') }}
        - cython
        - git
        - gitpython
        - if: linux
          then: patchelf
        - pip
        - pytest
        - pytest-mock
        - wheel
    script:
      - pip check
      - export CPPFLAGS=${CPPFLAGS//-DNDEBUG/}
      - pytest tests -vv

about:
  summary: Meson Python build backend (PEP 517)
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/mesonbuild/meson-python
  documentation: https://meson-python.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - awvwgk
    - rgommers

